[project]
name = "websem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama==0.4.6",
    "django==5.1.7",
    "python-dotenv==1.0.1",
    "sqlalchemy==2.0.39",
]
